application:
  name: checker
  environment: development

server:
  address: ":8080"

status:
  enabled: true
  address: ":8889"
  profiling: true

logger:
  level: info # one of: debug, info, warn, error
  # Format of the logs
  format: json # one of: json, text

versions:
  enabled: false
  endpoint: /versions
  resources:
    - name: cmk
      url: http://cmk.services.svc.cluster.local:8888/version

healthcheck:
  endpoint: "/healthz"
  enabled: true
  refreshDuration: 3s
  cluster:
    enabled: true
    resources:
      - name: localhost
        url: http://localhost:8888/probe/readiness
        retry:
          maxRetries: 3
        checks:
          - type: Equal #oneof: Contains, RegularExpression, Prefix, Suffix, Equal
            source: ResponseStatus #oneof: ResponseBody, ResponseStatus
            value: "200 OK"
#      - name: envoyproxy-ingress-gateway
#        url: http://envoyproxy-ingress-gateway.envoy-gateway-system.svc:8888/ready
#        checks:
#          - type: Equal #oneof: Contains, RegularExpression, Prefix, Suffix, Equal
#            source: ResponseStatus #oneof: ResponseBody, ResponseStatus
#            value: "200 OK"
#      - name: envoyproxy-ingress-certificate-gateway
#        url: http://envoyproxy-ingress-certificate-gateway.envoy-gateway-system.svc:8888/ready
#        retry:
#          maxRetries: 3
#        checks:
#          - type: Equal #oneof: Contains, RegularExpression, Prefix, Suffix, Equal
#            source: ResponseStatus #oneof: ResponseBody, ResponseStatus
#            value: "200 OK"
#      - name: envoy-gateway
#        url: http://envoy-gateway.envoy-gateway-system.svc:8888/healthz
#        retry:
#          maxRetries: 3
#        checks:
#          - type: Equal #oneof: Contains, RegularExpression, Prefix, Suffix, Equal
#            source: ResponseStatus #oneof: ResponseBody, ResponseStatus
#            value: "200 OK"
  kubernetes:
    enabled: false
    resources:
      - name: livez-verbose
        url: /livez?verbose
        checks:
          - type: Exact #oneof: Contains, RegularExpression, Prefix, Suffix, Equal
            source: ResponseStatus #oneof: ResponseBody, ResponseStatus
            value: "200 OK"
  linkerd:
    enabled: false
    controlPlaneNamespace: linkerd
    dataPlaneNamespace: linkerd
    cniNamespace: linkerd-cni
    retryDeadline: 300
    cniEnabled: false
    output: short #One of: table, json, short
    checks:
      - kubernetes-api
      - kubernetes-version
      - linkerd-version
      - linkerd-control-plane-proxy
      - linkerd-config
      - linkerd-identity

