version: 3

run: once
method: checksum

vars:
  CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/test/...'

includes:
  shared:
    taskfile: hack/common/Taskfile_library.yaml
    flatten: true

tasks:
  nothing: # This is executed if 'task' is called without any arguments.
    silent: true
    deps:
      - help

