version: 3

run: once
method: checksum

includes:
  shared:
    taskfile: hack/common/Taskfile_service.yaml
    flatten: true
    excludes:
      - gen:generate
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/test/...'
      COMPONENTS: 'checker'
      REPO_URL: 'https://github.com/openmkcm/checker'
      GENERATE_DOCS_INDEX: "false"
      ENVTEST_REQUIRED: "false"

tasks:
  list-files:
    desc: "List all file."
    requires:
      vars:
        - COMPONENTS
    cmds:
      - for:
          var: COMPONENTS
          as: COMPONENT
        cmd: 'ls -l {{.ROOT_DIR2}}/cmd/{{.COMPONENT}}'


