name: Git

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  release:
    uses: openkcm/build/.github/workflows/release.svc.yaml@main
    secrets: inherit
